name: release the javascript sdk

on:
  release:
    types: [created]

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm run test
      - run: npm run build
      - name: Deploy
        run: npm run deploy:ci
