name: release the javascript sdk

on:
  release:
    types: [created]

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  release-code:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Config
        run: |
          git config --global user.email "chu2815@hotmail.com"
          git config --global user.name "ianccy"
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm install
      - name: Unit-Test
        run: npm run test
      - name: Build Code
        run: npm run build
      - name: Upload to GitHub Repository
        run: npm run deploy:ci
